# Generated by Django 4.2.7 on 2023-11-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parriya', '0003_usuario_delete_usuario1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
