# Generated by Django 4.2.7 on 2023-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parriya', '0004_rename_contraseña_usuario_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('re_title', models.CharField(max_length=255)),
                ('re_desc', models.TextField()),
                ('re_image', models.ImageField(null=True, upload_to='static/img/')),
                ('re_total_group', models.IntegerField()),
                ('re_minutes', models.IntegerField()),
                ('re_difficulty', models.IntegerField(choices=[(0, 'Muy Fácil'), (1, 'Fácil'), (2, 'Intermedio'), (3, 'Dífil'), (4, 'Muy Díficil')], default=0)),
                ('re_slug', models.CharField(max_length=512)),
                ('re_status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
