# Generated by Django 4.2.7 on 2023-11-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parriya', '0005_recetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrilleros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pa_name', models.CharField(max_length=255)),
                ('pa_desc', models.TextField()),
                ('pa_profile', models.ImageField(null=True, upload_to='static/img/parrillero/profile')),
                ('pa_slug', models.CharField(max_length=512)),
                ('pa_status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
