# Generated by Django 4.2.4 on 2023-11-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parriya', '0006_parrilleros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('idDispo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaDispo', models.DateField()),
                ('horario', models.CharField(choices=[('manana', '09:00 - 13:59'), ('tarde', '14:00 - 18:59'), ('noche', '19:00 - 01:59')], max_length=30)),
            ],
        ),
    ]
