# Generated by Django 4.2.5 on 2023-12-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parriya', '0007_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('nSolicitante', models.CharField(max_length=50)),
                ('nParrillero', models.CharField(max_length=50)),
                ('fechaReserva', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'DISPONIBLE'), ('ocupado', 'OCUPADO')], default=2, max_length=15),
            preserve_default=False,
        ),
    ]
